services:
    Hal\Bundle\PhpMetricsCollector\Collector\PhpMetricsCollector:
        tags:
            -
                name:     data_collector
                template: '@PhpMetricsCollector/Collector/collector.html.twig'
                # must match the value returned by the getName() method
                id:       'phpmetrics_collector'
                # optional priority
                # priority: 300
        public: false
        arguments: ['@kernel']
