sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - 7.2
 - hhvm
 - nightly

allow_failures:
 - php: hhvm
 - php: nightly

env:
  global:
    - EXECUTE_CS_CHECK=false
    - TEST_COVERAGE=false
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""
    - SYMFONY_VERSION="^2.2"
    - SYMFONY_VERSION="^3.0"
    - SYMFONY_VERSION="^4.0"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: DEPENDENCIES="" SYMFONY_VERSION="^4.0" EXECUTE_CS_CHECK=true TEST_COVERAGE=true
  exclude:
    - php: 7.2
      env: DEPENDENCIES="" SYMFONY_VERSION="^4.0"

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update
  - if [[ -n "$SYMFONY_VERSION ]]; then composer require "symfony/http-kernel:$SYMFONY_VERSION" "symfony/dependency-injection:$SYMFONY_VERSION" ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --no-update satooshi/php-coveralls:dev-master ; fi

install:
  - travis_retry composer update --no-interaction --prefer-dist $DEPENDENCIES
  - composer info -i

before_script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then mkdir -p "$HOME/.php-cs-fixer" ; fi

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml ; else vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then vendor/bin/phpcs --standard=PSR2 --ignore=testing/application/cache/*,testing/application/AppKernel.php src testing ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v ; fi
